[package]
name = "cpp_core"
edition = "2018"
version = "0.5.0"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
description = "Utilities for interoperability with C++"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-qt/ritual"

[dependencies]
libc = "0.2"
