__common: &common
    language: rust
    rust: 1.34.2
    script: scripts/ci/travis/run.bash
    cache:
        directories:
#        - $HOME/.cargo
#        - $HOME/.rustup
#        - $HOME/ritual_temp_test_dir
        - target

matrix:
    include:
    -   <<: *common
        os: linux
        dist: trusty
    -   <<: *common
        os: osx
    -   <<: *common
        os: windows
