__common: &common
    language: rust
    rust: 1.38.0
    script: scripts/travis/run.bash
    cache:
        directories:
        - target
        - $HOME/ritual_temp_test_dir/test_full_run/workspace/target

matrix:
    include:
    -   <<: *common
        os: linux
        dist: trusty
    -   <<: *common
        os: osx
    -   <<: *common
        os: windows
        rust: 1.38.0-x86_64-pc-windows-msvc
