__common: &common
    language: rust
    rust: stable
    cache:
        directories:
        - $HOME/.cargo
        - $HOME/.rustup
        - $HOME/ritual_temp_test_dir
        - target

matrix:
    include:
    -   <<: *common
        os: linux
        dist: trusty
        script:
        - sudo apt-get install llvm-3.8 libclang-3.8-dev --yes --force-yes
        - scripts/ci/travis/run.bash
    -   <<: *common
        os: osx
        script: scripts/ci/travis/run.bash

