[package]
name = "qt_ritual_build"
edition = "2018"

# when changing this version, update `qt_generator/qt_generator/src/versions.rs`
version = "0.2.4"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
license = "MIT"
description = "Build script implementation for Rust Qt crates"
repository = "https://github.com/rust-qt/cpp_to_rust/tree/master/qt_generator/qt_build_tools"

[dependencies]
ritual_build = { version = "0.2.3", path = "../ritual_build" }
qt_ritual_common = { version = "0.2.3", path = "../qt_ritual_common" }
